note-id: 339
note-name: "&r&e$&6{VALUE} &enote"
note-lore: ["&r&4Clic-droit &cdéposer cette note", "&r&cCréé par: &4{CREATOR}"]
error-execute-ingame: "&cS'il vous plaît exécuter cette commande dans le jeu"
error-empty-argument: "&e&lUsage: &r&7/withdraw {value} [compter]"
withdraw-sucess: "&a&lSuccès: &r&7tu as retiré ${TOTAL_WITHDRAW}"
error-value-invalid: "&c&lErreur: &r&7veuillez fournir un nombre supérieur à 0."
error-insufficient-money: "&c&lErreur: &r&7le joueur n'a pas assez d'argent."
error-invalid-argument: "&c&lErreur: &r&7argument invalide donné."
deposit-succes: "&a&lSuccès! &r&7tu as déposé ${VALUE} à votre compte."
error-note-incompatible: "&c&lErreur: &r&7c'est une note obsolète."
error-note-invalid: "&c&lErreur: &r&7ce n'est pas une note valide."
reload-success: "&a&lSuccès! &r&7fichier de configuration rechargé."
validate-succes: "&a&lSuccès! &r&17cette note a été validée."
devalidate-succes: "&a&lSuccès! &r&17cette note a été dévaluée."
validate-error: "&c&lErreur: &r&7tu ne peux pas valider ça."
devalidate-error: "&c&lErreur: &r&7vous ne pouvez pas dévaluer ce."
note-check-valid: "&9&lRésultat: &r&7c'est une note valide."
note-check-invalid: "&9&lRésultat: &r&7ce n'est pas une note valide."
error-nopermission: "&c&lErreur: &r&7vous n'avez pas la permission d'exécuter cette."
unknown-command: "&6&l{FULLNAME} &r&e--- Commands\n&c/banknotes check &r&7- Vérifiez si la note que vous tenez est valide\n&c/banknotes admin &r&7- Afficher toutes les commandes admin"
unknown-command-admin: "&6&l{FULLNAME} &r&e--- Admin commands\n&c/banknotes admin reload &r&7- Recharger la configuration de ce plugin\n&c/banknotes admin validate &r&7- Rendre valide une note dévaluée\n&c/banknotes admin devalidate &r&7- Rendre une note invalide"
economyid: "economyid"
econid-compatibility: true